import React from 'react';
import { Link } from 'react-router-dom';
import { Triangle, Shield, Key, Cpu, Zap, Activity, Code, ChevronRight, Check } from 'lucide-react';

export default function LandingPage() {
  return (
    <div>
      <div className="bg-spotlight"></div>

      {/* Navbar */}
      <nav className="navbar">
        <Link to="/" className="logo"><Triangle size={24} fill="#4f46e5" strokeWidth={0} /> One Smarter</Link>
        <div className="nav-menu">
          <a href="#" onClick={(e) => { e.preventDefault(); window.scrollTo({top: 0, behavior: 'smooth'}); window.history.replaceState(null, '', '/'); }} className="nav-item">Home</a>
          <a href="#features" className="nav-item">Platform</a>
          <a href="#architecture" className="nav-item">Developers</a>
          <a href="#faq" className="nav-item">FAQ</a>
          <Link to="/security" className="nav-item">Security</Link>
        </div>
        <div className="nav-actions">
          <Link to="/login" className="nav-item">Log In</Link>
          <Link to="/register" className="btn-primary">Get Started</Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="hero">
        <div className="hero-badge">
          <span style={{width: '8px', height: '8px', background: '#ec4899', borderRadius: '50%', display: 'inline-block'}}></span>
          v1.0.5 Subscriber Agent is now available
        </div>
        <h1>Automate Portfolios with <br/><span className="text-gradient">Zero-Trust Security.</span></h1>
        <p>A powerful execution engine for quantitative traders. Fetch cryptographically signed mathematical targets, verify them locally, and execute across top brokerages instantly.</p>
        <div className="hero-buttons">
          <Link to="/register" className="btn-primary btn-large">
            Download Agent <ChevronRight size={18} />
          </Link>
          <a href="#architecture" className="btn-secondary btn-large">
            Read the Documentation
          </a>
        </div>
      </section>

      {/* Trust Badges */}
      <div className="trust-section" style={{ overflow: 'hidden' }}>
        <p className="trust-text">Integrates directly with industry leaders</p>
        <div className="marquee-wrapper">
          <div className="marquee-track">
            {/* First Set */}
            <span>ALPACA</span>
            <span>Robinhood</span>
            <span>TRADIER</span>
            <span>yFinance</span>
            <span>INTERACTIVE BROKERS</span>
            <span>POLYGON.IO</span>
            {/* Duplicate Set for Seamless Loop */}
            <span>ALPACA</span>
            <span>Robinhood</span>
            <span>TRADIER</span>
            <span>yFinance</span>
            <span>INTERACTIVE BROKERS</span>
            <span>POLYGON.IO</span>
          </div>
        </div>
      </div>
      
      {/* Features */}
      <section id="features" className="features-section">
        <div className="section-header">
          <h2>Enterprise-grade infrastructure.</h2>
          <p>Built for institutions, accessible to retail. Everything you need to automate portfolio rotation with absolute peace of mind.</p>
        </div>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon-wrapper icon-1">
              <Shield size={28} />
            </div>
            <h3>Zero-Trust Architecture</h3>
            <p>Every payload is signed with an Ed25519 Public Key. The agent strictly verifies the signature and expiration windows locally.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon-wrapper icon-2">
              <Cpu size={28} />
            </div>
            <h3>Local Python Agent</h3>
            <p>Your broker API keys never leave your machine. The lightweight agent pulls targets and executes directly from your IP address.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon-wrapper icon-3">
              <Activity size={28} />
            </div>
            <h3>Human-in-the-loop</h3>
            <p>Never lose control. Review all proposed portfolio rebalancing math generated by the backend before manually approving trades.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon-wrapper icon-4">
              <Zap size={28} />
            </div>
            <h3>Multi-Broker Ready</h3>
            <p>Native connectors for Alpaca API, Robinhood, and Tradier. Seamlessly switch brokers with a single configuration flag.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon-wrapper icon-5">
              <Key size={28} />
            </div>
            <h3>Replay Protection</h3>
            <p>Strict monotonic sequence IDs ensure that stale or duplicated payloads are instantly rejected by the agent.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon-wrapper icon-6">
              <Code size={28} />
            </div>
            <h3>Developer API</h3>
            <p>Write your own math engine and publish your own JSONs. The agent is entirely agnostic to your internal strategy.</p>
          </div>
        </div>
      </section>

      {/* Architecture Terminal */}
      <section id="architecture" className="architecture-section">
        <div className="arch-container">
          <h2 style={{ fontSize: '40px', fontWeight: '800', letterSpacing: '-1px', color: 'var(--text-main)', marginBottom: '16px' }}>Verify before you execute.</h2>
          <p style={{ fontSize: '20px', color: 'var(--text-muted)', maxWidth: '600px', margin: '0 auto', fontWeight: '500' }}>
            We've abstracted away the complexity of secure message parsing. Just run the command in your terminal.
          </p>
          
          <div className="terminal">
            <div className="terminal-head">
              <div className="terminal-dot dot-r"></div><div className="terminal-dot dot-y"></div><div className="terminal-dot dot-g"></div>
            </div>
            <div className="terminal-body">
              <div><span className="t-prompt">~</span> <span className="t-cmd">subscriber_agent sync --broker alpaca</span></div>
              <div><span className="t-dim">[10:14:22.401]</span> <span className="t-info">FETCH</span> Downloading payload seq_24 from publisher...</div>
              <div><span className="t-dim">[10:14:22.842]</span> <span className="t-success">PASS</span>  Ed25519 cryptographic signature verified.</div>
              <div><span className="t-dim">[10:14:22.843]</span> <span className="t-success">PASS</span>  Monotonic sequence is forward (24 &gt; 23).</div>
              <div><span className="t-dim">[10:14:22.850]</span> <span className="t-info">MATH</span>  Calculated delta: +14 shares XLV, -2 shares XLF.</div>
              <br/>
              <div><span className="t-dim">[10:14:22.852]</span> <span className="t-warn">WAIT</span>  Trades parked in dashboard. Awaiting manual HITL approval.</div>
            </div>
          </div>
        </div>
      </section>

      
      {/* Testimonials */}
      <section className="testimonials">
        <div className="section-header">
          <h2>Trusted by Quantitative Traders</h2>
          <p>See why portfolio managers are switching to local secure execution.</p>
        </div>
        <div className="testi-grid">
          <div className="testi-card">
            <div className="testi-stars">★★★★★</div>
            <p className="testi-text">"The zero-trust cryptographic verification gives me peace of mind. I know exactly what math the publisher ran, and my API keys stay safely on my laptop."</p>
            <div className="testi-author">
              <div className="testi-avatar" style={{background: 'linear-gradient(135deg, #4f46e5, #ec4899)'}}>A</div>
              <div className="testi-info"><h4>Alex M.</h4><p>Retail Quant Trader</p></div>
            </div>
          </div>
          <div className="testi-card">
            <div className="testi-stars">★★★★★</div>
            <p className="testi-text">"The monotonic sequence protection actually saved my portfolio during a network glitch when duplicate payloads were broadcast. Brilliant engineering."</p>
            <div className="testi-author">
              <div className="testi-avatar" style={{background: 'linear-gradient(135deg, #0ea5e9, #38bdf8)'}}>S</div>
              <div className="testi-info"><h4>Sarah T.</h4><p>Algorithmic Investor</p></div>
            </div>
          </div>
          <div className="testi-card">
            <div className="testi-stars">★★★★★</div>
            <p className="testi-text">"I love the Human-in-the-Loop dashboard. It parks the trades, shows me the delta calculations, and waits for me to click approve before hitting Alpaca."</p>
            <div className="testi-author">
              <div className="testi-avatar" style={{background: 'linear-gradient(135deg, #f59e0b, #fbbf24)'}}>D</div>
              <div className="testi-info"><h4>David R.</h4><p>Fund Manager</p></div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="faq-section">
        <div className="section-header">
          <h2>Frequently Asked Questions</h2>
          <p>Everything you need to know about the platform.</p>
        </div>
        <div className="faq-grid">
          <div className="faq-item">
            <h4><Shield size={20} color="#4f46e5" /> Do you have access to my brokerage account?</h4>
            <p>Absolutely not. The Publisher Agent backend only calculates mathematical allocations (e.g., XLF: 30%, AAPL: 10%) and signs them. Your API keys are stored locally on your machine within the Subscriber Agent application.</p>
          </div>
          <div className="faq-item">
            <h4><Cpu size={20} color="#ec4899" /> Which brokers do you support?</h4>
            <p>The local Subscriber Agent currently features native connectors for Alpaca API, Robinhood, and Tradier. We also provide a Mock Broker for paper-trading and strategy testing.</p>
          </div>
          <div className="faq-item">
            <h4><Activity size={20} color="#0ea5e9" /> Can trades execute automatically without me?</h4>
            <p>By default, the system operates in 'Human-in-the-Loop' (HITL) mode. The agent calculates delta-shares but parks the execution until you click 'Approve' on your local dashboard. Fully autonomous mode can be enabled in settings.</p>
          </div>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="cta-section">
        <div className="cta-box">
          <h2>Ready to automate?</h2>
          <p>Download the local Subscriber Agent today and start executing cryptographically secure trades directly from your machine.</p>
          <Link to="/register" className="cta-btn">Create Free Account <ChevronRight size={20} /></Link>
        </div>
      </section>

      {/* Footer */}
      
      <footer className="footer" style={{padding: '60px 20px', borderTop: '1px solid var(--border-color)', background: 'white'}}>
        <div className="footer-grid" style={{maxWidth: '1000px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '40px'}}>
          
          <div>
            <div style={{display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px', fontWeight: '800'}}>
              <Triangle size={20} fill="var(--primary)" strokeWidth={0}/> One Smarter
            </div>
            <p style={{color: 'var(--text-muted)', fontSize: '14px', lineHeight: '1.6'}}>Automating quantitative strategies with zero-trust security.</p>
          </div>
          
          <div>
            <h4 style={{fontWeight: '700', marginBottom: '20px'}}>Product</h4>
            <ul style={{listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '12px'}}>
              <li><Link to="/download" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Download Agent</Link></li>
              <li><Link to="/integrations" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Integrations</Link></li>
              <li><Link to="/pricing" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Pricing</Link></li>
              <li><Link to="/changelog" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Changelog</Link></li>
            </ul>
          </div>
          
          <div>
            <h4 style={{fontWeight: '700', marginBottom: '20px'}}>Developers</h4>
            <ul style={{listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '12px'}}>
              <li><Link to="/docs" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Documentation</Link></li>
              <li><Link to="/api-reference" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>API Reference</Link></li>
              <li><Link to="/security" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Security Model</Link></li>
              <li><a href="https://github.com/onesmarter" target="_blank" rel="noreferrer" style={{color: 'var(--primary)', textDecoration: 'none'}}>GitHub</a></li>
            </ul>
          </div>
          
          <div>
            <h4 style={{fontWeight: '700', marginBottom: '20px'}}>Company</h4>
            <ul style={{listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '12px'}}>
              <li><Link to="/about" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>About</Link></li>
              <li><Link to="/blog" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Blog</Link></li>
              <li><Link to="/terms" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Terms</Link></li>
              <li><Link to="/privacy" style={{color: 'var(--text-muted)', textDecoration: 'none'}}>Privacy</Link></li>
            </ul>
          </div>
          
        </div>
      </footer>

    </div>
  );
}
