# Generated by Django 6.0.7 on 2026-08-26 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('effective_session', models.DateField()),
                ('model_id', models.CharField(default='rotation-core', max_length=50)),
                ('portfolio_id', models.CharField(default='core', max_length=50)),
                ('sleeve_allocation_pct', models.FloatField(default=100.0)),
                ('regime', models.CharField(max_length=50)),
                ('phase', models.CharField(max_length=50)),
                ('cash_percentage', models.FloatField()),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('FLOAT', 'Float'), ('INT', 'Integer'), ('STRING', 'String'), ('JSON', 'JSON')], max_length=10)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trading_date', models.DateField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adjusted_close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('source', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('symbol', 'trading_date')},
            },
        ),
        migrations.CreateModel(
            name='PublishedJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_path', models.CharField(max_length=255)),
                ('canonicalization', models.CharField(default="json.dumps(sort_keys=True, separators=(',',':'))", max_length=100)),
                ('signature_alg', models.CharField(default='Ed25519', max_length=50)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('key_id', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_json', to='PublisherApp.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('INFO', 'Info')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='PublisherApp.portfolio')),
                ('strategy_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='PublisherApp.strategyrun')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='strategy_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='PublisherApp.strategyrun'),
        ),
        migrations.CreateModel(
            name='TechnicalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trading_date', models.DateField()),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('moving_average', models.FloatField(blank=True, null=True)),
                ('relative_strength', models.FloatField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('breadth_score', models.FloatField(blank=True, null=True)),
                ('sector_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('symbol', 'trading_date')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('target_percentage', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='PublisherApp.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('model_id', 'sequence')},
        ),
    ]
