# Generated by Django 5.2.14 on 2026-08-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriberApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaliciousActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(default='UNAUTHORIZED_TOKEN_ACCESS', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_breaches', to='SubscriberApp.subscriber')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
