import os
import json
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from PublisherApp.models import PublishedJson
from django.conf import settings
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from SubscriberApp.api.permissions import IsActiveSubscriber

class LatestTargetAPIView(APIView):
    """
    SaaS API Endpoint to serve the latest published JSON target.
    Locked down: Requires a valid Token in the Authorization header.
    """
    
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated, IsActiveSubscriber]
    
    def get(self, request, *args, **kwargs):
        try:
            # Always get the single most recent publication
            latest_publish = PublishedJson.objects.latest('published_at')
            
            # Read the physical file generated by the Math Engine
            json_file_path = os.path.join(settings.BASE_DIR, latest_publish.json_path)
            
            if not os.path.exists(json_file_path):
                return Response(
                    {"error": "Latest target file not found on disk."}, 
                    status=status.HTTP_500_INTERNAL_SERVER_ERROR
                )
                
            with open(json_file_path, 'r') as f:
                json_data = json.load(f)
                
            # Return the exact JSON payload.
            # We don't use Django REST Framework's default JSONRenderer 
            # if we want to preserve exact canonical formatting, but since 
            # the desktop app verifies the 'document' block stringified exactly,
            # we can just return it as a dict and DRF will serialize it. 
            # Wait, actually, returning a Response(json_data) is perfect.
            
            return Response(json_data, status=status.HTTP_200_OK)
            
        except PublishedJson.DoesNotExist:
            return Response(
                {"error": "No targets have been published yet."}, 
                status=status.HTTP_404_NOT_FOUND
            )
        except Exception as e:
            return Response(
                {"error": f"An unexpected error occurred: {str(e)}"}, 
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )
